"""Catalog publication limits derived from Telegram runtime constraints."""

TELEGRAM_MEDIA_CAPTION_LIMIT = 1024
TELEGRAM_TEXT_MESSAGE_SAFE_LIMIT = 3900
CATALOG_DESCRIPTION_MAX_LEN = 600
REVIEW_TEXT_MAX_LEN = 4000
REVIEW_TEXT_WITH_MEDIA_MAX_LEN = 950
